version: "3.9"

services:
  
  api:
    image: fastapi/api
    build: api
    ports:
      - 8000:8080
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/data/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    user: "$UID:$GID"
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana

networks:
  default: 
    name: prometheus_grafana_demo
